"use client";

import Link from "next/link";
import { Cpu, CalendarClock, Wallet, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { usePlannerStore } from "@/store/planner-store";
import type { BlueprintData } from "@/lib/ai/types";

function buildSections(blueprint: BlueprintData) {
  return [
    {
      icon: Cpu,
      title: "Compute Requirements",
      description: "Recommended configuration based on your conversation",
      items: [
        { label: "Workload type", value: blueprint.workloadType },
        { label: "GPU configuration", value: blueprint.gpuConfiguration },
        { label: "Hardware condition", value: blueprint.hardwareCondition },
      ],
    },
    {
      icon: CalendarClock,
      title: "Deployment Plan",
      description: "Timeline and location considerations",
      items: [
        { label: "Target timeline", value: blueprint.targetTimeline },
        { label: "Location preference", value: blueprint.locationPreference },
        { label: "Deployment support", value: blueprint.deploymentSupport },
      ],
    },
    {
      icon: Wallet,
      title: "Estimated Investment",
      description: "Commercial parameters for supplier matching",
      items: [
        { label: "Estimated budget", value: blueprint.estimatedBudget },
        { label: "Commercial model", value: blueprint.commercialModel },
        { label: "Currency", value: blueprint.currency },
      ],
    },
  ];
}

export function BlueprintView() {
  const blueprint = usePlannerStore((state) => state.blueprint);

  if (!blueprint) {
    return (
      <Card>
        <CardContent className="flex flex-col items-center py-12 text-center">
          <h2 className="text-lg font-semibold">No blueprint yet</h2>
          <p className="text-muted-foreground mt-2 max-w-sm text-sm">
            Start a conversation with the AI Planner to generate your infrastructure blueprint.
          </p>
          <Button
            render={<Link href="/conversation" />}
            nativeButton={false}
            className="bg-brand text-brand-foreground hover:bg-brand/90 mt-6"
          >
            Start Planning
          </Button>
        </CardContent>
      </Card>
    );
  }

  const sections = buildSections(blueprint);

  return (
    <div className="space-y-6">
      <div className="grid gap-6 sm:grid-cols-3">
        {sections.map((section) => (
          <Card key={section.title}>
            <CardHeader>
              <div className="bg-brand/10 text-brand mb-2 flex size-9 items-center justify-center rounded-lg">
                <section.icon className="size-4.5" aria-hidden="true" />
              </div>
              <CardTitle>{section.title}</CardTitle>
              <CardDescription>{section.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <dl className="space-y-2.5">
                {section.items.map((item) => (
                  <div key={item.label} className="flex items-center justify-between gap-4 text-sm">
                    <dt className="text-muted-foreground">{item.label}</dt>
                    <dd className="text-right font-medium">{item.value}</dd>
                  </div>
                ))}
              </dl>
            </CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardContent className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
          <div>
            <div className="flex items-center gap-2">
              <Badge className="bg-brand/10 text-brand">Ready</Badge>
              <p className="text-sm font-medium">Blueprint ready for supplier matching</p>
            </div>
            <p className="text-muted-foreground mt-1.5 text-sm">
              Turn this blueprint into an RFQ to reach the VELORA supplier network.
            </p>
          </div>
          <Button
            render={<Link href="/rfq" />}
            nativeButton={false}
            className="bg-brand text-brand-foreground hover:bg-brand/90 shrink-0"
          >
            Request Quote
            <ArrowRight className="size-4" aria-hidden="true" />
          </Button>
        </CardContent>
      </Card>

      <Separator />
      <p className="text-muted-foreground text-xs">
        Generated by the AI Planner from your conversation.
      </p>
    </div>
  );
}
